### PR TITLE
Fix part of #180: Add Content to onboarding Screen

### PR DESCRIPTION
**Pull request by Khushi-24**
## Explanation

Fixes https://github.com/CSwala/CSwala-android/issues/180

- Designed Illustration for Onboarding Screen
- Added Related Content

Short Video: https://user-images.githubusercontent.com/70067211/119319516-2f53bd00-bc98-11eb-8512-586dd0785e39.mp4

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adher to the contributing guidelines of the project.
- [x] The PR is made to the branch that's **called** "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".

### CODE REVIEW

**Review by riturajjain2000 — CHANGES_REQUESTED** [review]
Looks good , just change the Titles of each screen according to the tabs name i.e the names used in the app

**Comment by Khushi-24** [comment]
@riturajjain2000 Modified it. 

https://user-images.githubusercontent.com/70067211/119511140-c2bbe980-bd8f-11eb-8c36-b2d3608d3896.mp4

**Comment by riturajjain2000** [comment]
can you remove the text in the brackets form the 2 hackfeed pages?

**Comment by Khushi-24** [comment]
https://user-images.githubusercontent.com/70067211/119571693-4b0daf00-bdcf-11eb-980d-99ebebeee2f3.mp4

**Review by riturajjain2000 — APPROVED** [review]

**Pull request merged**
