### PR TITLE
#111 Added Edit Profile Option

### PR DESCRIPTION
**Pull request by RashikaJoshi-777**
## Checklist

- [ ] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adher to the contributing guidelines of the project.
- [x] The PR is made to the branch that's **called** "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".

### CODE REVIEW

**Comment by riturajjain2000** [comment]
Link the issue this PR fixes

**Review by riturajjain2000 — CHANGES_REQUESTED** [review]
- Remove the Edit Profile text from the top
- The Strings sources are not there add them 
- Also if we are updating the profile picture then it should be updated in the profile fragment also , so add that feature also

**Comment by RashikaJoshi-777** [comment]
> * Remove the Edit Profile text from the top
> * The Strings sources are not there add them
> * Also if we are updating the profile picture then it should be updated in the profile fragment also , so add that feature also

For updating the profile picture in the profile fragment also , when we update the photo it will get stored in the database and we will fetch the picture from the database so it will get updated that way and as of now we do not have access to the data stored in database so how  to add that feature.

**Comment by riturajjain2000** [comment]
> > * Remove the Edit Profile text from the top
> > * The Strings sources are not there add them
> > * Also if we are updating the profile picture then it should be updated in the profile fragment also , so add that feature also
> 
> For updating the profile picture in the profile fragment also , when we update the photo it will get stored in the database and we will fetch the picture from the database so it will get updated that way and as of now we do not have access to the data stored in database so how to add that feature.

DM me your details over discord, will grant you access

**Pull request closed without merging**
