### PR TITLE
Fix #93: Enable login progress dialog

### LINKED ISSUE #93: Enable progress dialog while logging in
<div align = "center">
<h3> Enhances user experience while logging in. </h3>
Add progress dialog to the following login options.
<br>
         ⦿ Google 
         ⦿ Github 
         ⦿ Email 
</div>

### PR DESCRIPTION
**Pull request by GowthamGoush**
## Explanation
Fixes #93: Added progress dialog for login.

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adher to the contributing guidelines of the project.
- [x] The PR is made to the branch that's **called** "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".

### CODE REVIEW

**Review by riturajjain2000 — CHANGES_REQUESTED** [review]
Google Login is not working after this

**Comment by GowthamGoush** [comment]
Actually, it is working fine for me. Maybe it takes time, but I haven't made any changes to the code responsible for login.

**Comment by GowthamGoush** [comment]
Any updates?

**Comment by riturajjain2000** [comment]
Its working fine , but even after successful login , the toast is being displayed as 'something went wrong'

**Comment by GowthamGoush** [comment]
So I actually didn't work with any code concerned with that. Also, I didn't encounter any such behaviour despite multiple login tests.
Could you help me out with what should I do?

**Comment by GowthamGoush** [comment]
I actually found the issue. The issue seems to be from the fetch method of Explore and Portal fragments. Moreover, my commits in this PR don't seem to have any relation with this issue. So shall I raise an issue separately for this?

**Comment by ddvader44** [comment]
@GowthamGoush will you be raising a new PR, so we can close this

**Comment by GowthamGoush** [comment]
> @GowthamGoush will you be raising a new PR, so we can close this

Yeah, I'll create a new PR and raise an issue for this.

**Pull request closed without merging**
