### PR TITLE
Fixes #111 Added edit profile option 

### LINKED ISSUE #111: To add edit profile option
after the profile fragment is build i want to add edit profile option to the fragment [GSSOC'21]

### PR DESCRIPTION
**Pull request by RashikaJoshi-777**
#

## Explanation

  - Fixes #111 : Added edit profile option
 

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adher to the contributing guidelines of the project.
- [x] The PR is made to the branch that's **called** "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".

#111

### CODE REVIEW

**Comment by riturajjain2000** [comment]
resolve conflicts and properly fill the  PR desc

**Comment by riturajjain2000** [comment]
Which issue is this PR fixing ?

**Comment by RashikaJoshi-777** [comment]
> Which issue is this PR fixing ?

#111

**Comment by riturajjain2000** [comment]
> > Which issue is this PR fixing ?
> 
> #111

then link it

**Review by riturajjain2000 — APPROVED** [review]

**Pull request merged**
