### PR TITLE
Fix part of #bug-58

### LINKED ISSUE #58: Update The Launcher Icon

### PR DESCRIPTION
**Pull request by Khushi-24**
## Explanation
Fixes #58 
Launcher Icon Updated

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adher to the contributing guidelines of the project.
- [x] The PR is made to the branch that's **called** "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".

### CODE REVIEW

**Comment by Khushi-24** [comment]
@riturajjain2000 I have changed the icon as per the requirement Please have a look.

**Review by riturajjain2000 — CHANGES_REQUESTED** [review]
Remove the Text from the icon and link the issue

**Comment by Khushi-24** [comment]
> Remove the Text from the icon and link the issue

https://github.com/CSwala/CSwala-android/issues/58

**Comment by riturajjain2000** [comment]
> Remove the Text from the icon and link the issue

By linking the issue I meant , write "Fixes #issuemunber" in the PR desc.

**Review by riturajjain2000 — APPROVED** [review]

**Comment by Khushi-24** [comment]
> > Remove the Text from the icon and link the issue
> 
> By linking the issue I meant , write "Fixes #issue_number" in the PR desc.

Sorry, Now onwards I will take care.

**Pull request merged**
