### PR TITLE
Fix #107 : Fixed 'Community' ID Spelling

### LINKED ISSUE #107: Resource ID name has wrong spelling
There is s mistake in code where in MainActivity and Menu's BottomNavigation the community tab's ID is given in wrong spelling "commun**tiy**", assign me this I'll refractor it and make a PR.

### PR DESCRIPTION
**Pull request by fin1te**
Fixes #107 

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adher to the contributing guidelines of the project.
- [x] The PR is made to the branch that's **called** "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".

### CODE REVIEW

**Review by riturajjain2000 — CHANGES_REQUESTED** [review]
remove compiler and discord xml files

**Comment by fin1te** [comment]
> remove compiler and discord xml files

@riturajjain2000 done

**Review by riturajjain2000 — CHANGES_REQUESTED** [review]
They are still showing in the changed files

**Comment by fin1te** [comment]
> They are still showing in the changed files. remove them from there

Oh thanks, I misread the requested changes the first time, remove those files.

**Review by riturajjain2000 — APPROVED** [review]

**Pull request merged**
