### PR TITLE
added news fragment

### PR DESCRIPTION
**Pull request by kunal299**
## Checklist

- [ ] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [ ] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [ ] The PR does not break any part of the existing code.
- [ ] The PR creator have carefully read & adher to the contributing guidelines of the project.
- [ ] The PR is made to the branch that's **called** "develop".
- [ ] The PR is made from a branch that is up-to-date with "develop".
- [ ] The PR's branch is based on "main" and not on any other branch.

### CODE REVIEW

**Comment by kunal299** [comment]
@riturajjain2000 Hey this pr is to update my forked repo

**Comment by riturajjain2000** [comment]
> @riturajjain2000 Hey this pr is to update my forked repo

Dont make this then , just rebase your branch

**Comment by kunal299** [comment]
@riturajjain2000 How to do that?

**Comment by riturajjain2000** [comment]
> @riturajjain2000 How to do that?

please search things on your own level before asking here , as it will help you more !

**Comment by kunal299** [comment]
@riturajjain2000 Hey i have synced it but it is saying that I am 2 commits ahead. Will it create any problem ?

**Comment by riturajjain2000** [comment]
> @riturajjain2000 Hey i have synced it but it is saying that I am 2 commits ahead. Will it create any problem ?

Check if those commits have any changes in any of the files y comparing it with the upstream , if not than its not a problem.
Also you can  close this.

**Pull request closed without merging**
