### PR TITLE
Refactoring

### LINKED ISSUE #94: Basic Refactoring Required
As many people are contributing it, will be good if we can refactor our code into few packages like
1. Common - Having Main Activity ,Login Activity ,OTP verification , splash screen and all common items.
2. Fragments - Having all the frames and fragments under one package

Please Assign this to me and mark down accordingly.

### PR DESCRIPTION
**Pull request by hemant2705**
Refactoring all fragments under package name Fragment,
and Activities under package named Activities.

## Explanation
I just refactored the code snippets and move them under several packages.
It is basically done to make code more readable .
Fixes #94 

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adher to the contributing guidelines of the project.
- [x] The PR is made to the branch that's **called** "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "main" and not on any other branch.

### CODE REVIEW

**Comment by ddvader44** [comment]
Add progress bar to login activity please!

**Review by riturajjain2000 — CHANGES_REQUESTED** [review]
Refactor all the activity in a `Activity` directory

**Comment by hemant2705** [comment]
Can you review it once now?

**Review by riturajjain2000 — APPROVED** [review]

**Comment by riturajjain2000** [comment]
Just do things according to the PR template , checkboxes should be ticked and whats instructed in them should be done

**Comment by hemant2705** [comment]
I made things according to PR template .
Please check and let me know if anything else needed.

**Pull request merged**
