### PR TITLE
#93 Progress bar Visibility

### LINKED ISSUE #93: Enable progress dialog while logging in
<div align = "center">
<h3> Enhances user experience while logging in. </h3>
Add progress dialog to the following login options.
<br>
         ⦿ Google 
         ⦿ Github 
         ⦿ Email 
</div>

### PR DESCRIPTION
**Pull request by hemant2705**
## Explanation
There were few places where a progress bar was required. So implemented that
Fixes #93

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adher to the contributing guidelines of the project.
- [x] The PR is made to the branch that's **called** "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".

### CODE REVIEW

**Review by riturajjain2000 — CHANGES_REQUESTED** [review]
Link the issue which is fixed by this PR

**Comment by hemant2705** [comment]
#93

**Review by riturajjain2000 — APPROVED** [review]

**Review by riturajjain2000 — APPROVED** [review]

**Comment by GowthamGoush** [comment]
Actually, issue #93 has been assigned to me, and also, this pull request doesn't seem to fulfil the issue.

**Comment by riturajjain2000** [comment]
This will not be considered , you can make your own PR @GowthamGoush

**Comment by GowthamGoush** [comment]
Hey, @hemant2705, it's totally fine since you made this by mistake. I still remember committing similar mistakes when I was new to open-source 😜. Just make sure that you raise an issue before making a pr.

**Comment by hemant2705** [comment]
Yeah, actually I understand it's necessary to get assigned first for the issue but earlier one of my issue had been solved by someone while I was in stage of merging the conflicts.(referring #102).

**Comment by riturajjain2000** [comment]
You should have pinged me right away , You can make the PR for that now , reopening it and reverting that PR !

**Comment by riturajjain2000** [comment]
> Yeah, actually I understand it's necessary to get assigned first for the issue but earlier one of my issue had been solved by someone while I was in stage of merging the conflicts.(referring #102).

It was a beginner issue and you took more than 5 days , that's why😅
Actually there are more participants than issues , and we cannot hold easy issue for this long

**Comment by GowthamGoush** [comment]
> > Yeah, actually I understand it's necessary to get assigned first for the issue but earlier one of my issue had been solved by someone while I was in stage of merging the conflicts.(referring #102).
> 
> It was a beginner issue and you took more than 5 days , that's why😅
> Actually there are more participants than issues , and we cannot hold easy issue for this long

Since I have mentioned email login as well, I was waiting for a fellow contributor to implement it to work on it. In fact, most of my issues are kind of dependent on some features to implement before I could work on them.

**Comment by GowthamGoush** [comment]
> Yeah, actually I understand it's necessary to get assigned first for the issue but earlier one of my issue had been solved by someone while I was in stage of merging the conflicts.(referring #102).

Omg! Just bring it to the notice of our mentors and maintainers. Again that contributor should have been new to open-source.

**Comment by hemant2705** [comment]
> > Yeah, actually I understand it's necessary to get assigned first for the issue but earlier one of my issue had been solved by someone while I was in stage of merging the conflicts.(referring #102).
> 
> @hemant2705 ,It was a beginner issue and you took more than 5 days , that's why😅
> Actually there are more participants than issues , and we cannot hold easy issue for this long

Actually the fault I did was..I was trying to resolve 2 issues with one pr.. And the second part was generating conflicts.. Hence you can see I closed the that pr. And did it again. 
As I am very new to vcs and github it will take time to learn up things. 
Not an issue! 🙃
Looking forward to contribute more and learn😅🙌.

**Pull request merged**
