### PR TITLE
Fix part of #bug-60

### PR DESCRIPTION
**Pull request by Khushi-24**
Issue-60 (Adding login with email functionality)

Explanation

Earlier the app consisted of login with google and GitHub functionality I have tried to add the login with email functionality 

First user need to Register himself(UserId would be added to firebase)
The user needs to log in.
When a user tries to login for the first time he/she needs to verify email first.
After email verification user can log in to the app.

Video:-
https://user-images.githubusercontent.com/70067211/112765452-e6caab00-902a-11eb-87dd-db56b2aab58c.mp4

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adher to the contributing guidelines of the project.
- [x] The PR is made to the branch that's **called** "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".

### CODE REVIEW

**Comment by Khushi-24** [comment]
Before implementing the code in the main app I had created a demo app. The code was working fine. When I implemented the code in the main app User is getting registered But the Toast message showing up is "Failed to Register! Try Again!". The code is the same as that of the demo app.
Link: https://github.com/Khushi-24/Firebase-Email-authentication-Demo. @riturajjain2000 can you please guide me a bit about this.

**Comment by riturajjain2000** [comment]
I think that the problem is that your SHA keys are not added in my project , if not , Dm them over discord

**Review by riturajjain2000 — CHANGES_REQUESTED** [review]
The Login is working fine and the user is getting authenticated , but after successful authentication also , Toast is showing is as failed . 

To check ,If you login and after the toast of failed login , press back , then you are transferred to the Main Activity

To do's
- Fix the intent and check why user is not being redirected to mainactivity
- All the intents should be in the Intent helper class

**Comment by Khushi-24** [comment]
@riturajjain2000 I have made the required changes. Please review the PR. The toast message error is also solved.

**Review by riturajjain2000 — CHANGES_REQUESTED** [review]
Still unable to log in or register. 
Also, add the animation to the login button like Gmail login and Github login and Add the mail logo as well

**Review by riturajjain2000 — APPROVED** [review]

**Review by riturajjain2000 — CHANGES_REQUESTED** [review]
Resolve the merge conflicts and Link the issue

**Comment by Khushi-24** [comment]
@riturajjain2000 Resolved Merge Conflicts

**Pull request merged**
