### PR TITLE
Fix #112 Adding calendar feature for CP

### LINKED ISSUE #112: Adding calendar feature for CP
As this app is to Get Latest Updates about Everything there exits in Computer Science, it will be good to add a feature with a calendar which shows all the contest from different websites (such as codeforces, codechef etc.) which will occur in upcoming dates and also shows which all contest a user attempted and which all a user missed also a reminder can be set for a contest (if user wants).      
please assign this issue to me

### PR DESCRIPTION
**Pull request by RashikaJoshi-777**
## Explanation

  - "Fixes #112 :" Adding calendar feature for CP
  
  

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adher to the contributing guidelines of the project.
- [x] The PR is made to the branch that's **called** "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".

### CODE REVIEW

**Comment by RashikaJoshi-777** [comment]
I made all the changes which you asked except the faang and dare2compete one .I will do that in a new PR. Please verify this and merge this if everything seems right to you.

**Comment by riturajjain2000** [comment]
Thanks , but can you please make these changes in the original PR only , and close this one

**Comment by RashikaJoshi-777** [comment]
May i close previous PR and kept this one if that doesn't bother you

**Comment by RashikaJoshi-777** [comment]
Ok i will keep that in mind from next time, sorry for inconvenience.

**Review by riturajjain2000 — APPROVED** [review]

**Pull request merged**
