### PR TITLE
#166 Add Best Section in Explore Fragment.

### PR DESCRIPTION
**Pull request by ANUJAGRAWAL2000**
## Explanation

In this I have added the BestPractice Adapter in Explore Fragment and on clicking any item an new activity will start having the items in recycler view and on clicking them URL will get open.
## Checklist

- [ ] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adher to the contributing guidelines of the project.
- [x] The PR is made to the branch that's **called** "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".

### CODE REVIEW

**Review by riturajjain2000 — CHANGES_REQUESTED** [review]
Looks good , just remove the "Best practices " Text from the top and make the description activity similar to techdata activity , i.e. remove the yellow background and change font syle

**Comment by ANUJAGRAWAL2000** [comment]
Remove the "Best Practices" Text means? I didn't get you!!

**Comment by ANUJAGRAWAL2000** [comment]
I have removed the "Best Practices" Text and make the Description Activity similar to Techdata Activity in respect of colour and font.

**Comment by riturajjain2000** [comment]
The best practices section is not visible anymore in the explore fragment ,  also the text  is still there in the beginner friendly section

**Review by riturajjain2000 — CHANGES_REQUESTED** [review]
You have to fetch data from DB , not hardcode it

**Pull request merged**
