### PR TITLE
Fix #102 Added explore fragment as default

### LINKED ISSUE #102: Default Fragment
Currently when app is opening their is no fragment shown and after clicking menu items it is showing the fragment content respectively.
setting a default fragment can help .
We can put explore fragment as our Default fragment and when app will restart we can it will open the explore fragment .

please assign this to me by adding tags accordingly

### PR DESCRIPTION
**Pull request by venkatesh1226**
## Explanation

Added Explore Fragment as default Fragment.

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adher to the contributing guidelines of the project.
- [x] The PR is made to the branch that's **called** "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".

### CODE REVIEW

**Comment by riturajjain2000** [comment]
Add Fixes 'bugnum ' in description and put a x in place of ✔ in the boxes , i.e. [x]

**Comment by venkatesh1226** [comment]
> Add Fixes 'bugnum ' in description and put a x in place of ✔ in the boxes , i.e. [x]

Done :)

**Comment by riturajjain2000** [comment]
you have not linked the issue yet

**Comment by venkatesh1226** [comment]
https://github.com/CSwala/CSwala-android/issues/102 
this is the issue I worked on

**Comment by venkatesh1226** [comment]
> you have not linked the issue yet

https://github.com/CSwala/CSwala-android/issues/102 this is the issue I worked on.

**Review by riturajjain2000 — APPROVED** [review]

**Pull request merged**
