### PR TITLE
issue#143

### LINKED ISSUE #143: Problem in profile fragment
The whole page of profile fragment does't appere and does't scroll 
Please assign this issue to me (gssoc 21) 
Screenshot_20210331-213333_CS wala

### PR DESCRIPTION
**Pull request by hagerk720**
Fixes #143
make profile fragment suit small screens and show all buttons by scrolling which also fix the same thing in landscape mode
### Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x]  The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x]  The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x]  The PR does not break any part of the existing code.
- [x]  The PR creator have carefully read & adher to the contributing guidelines of the project.
- [x]  The PR is made to the branch that's called "develop".
- [x]  The PR is made from a branch that is up-to-date with "develop".

### CODE REVIEW

**Review by riturajjain2000 — APPROVED** [review]
Looks good , use the PR template and ink the issue and since you are make changes to the profile frag. , remove the 'MY PROFILE' text from the top , Also change the button style to match the other buttons in the app, (Login buttons)

**Comment by hagerk720** [comment]
Sorry but can you explain how to use PR tamplate and how to link the issue ?
Do i do new pull request ?

**Comment by riturajjain2000** [comment]
> Sorry but can you explain how to use PR tamplate and how to link the issue ?
> Do i do new pull request ?

The PR template suggests the best practices while making the PR, and after following them , tick the checkbox to let the maintainers that you have followed the best practices 

 To link the issue, say issue no. 57 write - "Fixes #57" in the Description of the PR

**Comment by hagerk720** [comment]
is that fine now ?

**Review by riturajjain2000 — APPROVED** [review]

**Pull request merged**
